import { chapter, completion, detour, step } from "../../core/schema.js?v=2026-08-12-guide-companion-v4";

const BASICS_LESSONS = Object.freeze([
  step({
    id: "introduction",
    title: "Prisma Generator Basics",
    body: "This guide will show you the basic steps for converting an image into the 3D meshes used to print a color lithophane.\n\nAlong the way, you will learn how Prisma Generator organizes images, palettes, settings, solve results, and print files. You can end this guide at any time.",
    target: null,
    overlayMode: "full-scrim",
    placements: [],
    allowPrevious: false,
    allowSkip: false,
    nextLabel: "Begin",
  }),
  step({
    id: "core-terminology",
    title: "Terminology",
    body: "There are two terms you should know before continuing:\n\n• A **palette** is a small set of colored filaments that can be layered together to produce the colors in a finished lithophane. They act like “primary colors” that Prisma combines to reproduce the colors in the source image.\n\n• A **solve** is Prisma’s process for deciding how to layer the filaments in a palette to recreate the appearance of an image.",
    target: null,
    placements: [],
  }),
  step({
    id: "lithophane-image-principle",
    title: "How a lithophane creates an image",
    body: "A lithophane forms an image by controlling how much light passes through each part of a thin printed panel. In a color lithophane, stacked filament colors and varying printed thickness work together to produce the colors and brightness you see.",
    target: null,
    overlayMode: "full-scrim",
    placements: [],
  }),
  step({
    id: "prisma-creation-overview",
    title: "How Prisma turns an image into a print",
    body: "Prisma begins with a source image and a palette of calibrated filaments. It determines a printable filament stack for each part of the image, predicts how those stacks will appear when lit, and turns the result into 3D meshes that a slicer can prepare for printing.",
    target: null,
    overlayMode: "full-scrim",
    placements: [],
  }),
  step({
    id: "workflow",
    title: "The Generator workflow",
    body: "Prisma’s numbered workflow moves from a source image to printable files:\n\nImage → Palette → Preview → Export\n\nSettings are available throughout the workflow and affect the next solve. You can start a solve from any workflow page; it uses the prepared image, active palette, and current settings at the moment it begins.\n\nEach stage will be explained in more detail as you move through this guide.",
    target: "workflow.overview",
    placements: ["bottom", "right", "top", "left"],
    viewportAnchor: "center",
  }),
  step({
    id: "printer-select",
    title: "Select the Tutorial Printer profile",
    body: "This guide uses the Tutorial Printer profile to ensure that all learners get the same experience.\n\nSelect Tutorial Printer from the Active printer list.",
    target: "sidebar.active-printer",
    placementGroup: "basics-printer",
    viewportAnchor: "center",
    completionMode: completion("event", {
      event: "printer.active-changed",
      predicate_id: "basics.tutorial-printer-active",
      accept_preexisting: true,
    }),
  }),
  step({
    id: "tutorial-extrusion-width",
    title: "Extrusion Width selection",
    body: "Extrusion Width is the line width you will use in your slicer. Prisma uses it to keep horizontal features printable and to define the available Solve Pitch values.\n\nThis guide uses the saved 0.40 mm Extrusion Width under the 0.40 mm nozzle. Select it to proceed.",
    target: "sidebar.active-extrusion-width",
    placementGroup: "basics-printer",
    viewportAnchor: "center",
    enterActions: [
      { action: "printer.select_print_setup", input: { nozzle_id: "nozzle-200", extrusion_width_um: 200 } },
    ],
    completionMode: completion("event", {
      event: "printer.extrusion-width-changed",
      predicate_id: "basics.tutorial-extrusion-width-active",
      accept_preexisting: false,
    }),
    allowSkip: false,
  }),
  step({
    id: "image-introduction",
    title: "Image: prepare the source",
    body: "**Image** is where you define what you want your lithophane to look like and how big it will be. Prisma uses the resulting image as the visual target for every other part of its process.",
    target: "workflow.image",
    reveal: "workflow.image-page",
    placements: ["bottom", "right", "top", "left"],
  }),
  step({
    id: "image-library",
    title: "Adding images to the Image Library",
    body: "The Image Library contains the images available for use in Prisma. Its contents reflect the image files stored in Prisma’s Images folder.\n\nUse **Add Image** to import one or more images without leaving the app. Use **Open Folder** to view or manage the Images folder in your system file browser.",
    note: {
      label: "Images folder",
      text: "{{imagesFolder}}",
    },
    target: "image.library-import",
    placementGroup: "basics-image-library",
  }),
  step({
    id: "image-library-maintenance",
    title: "Updating and expanding the library",
    body: "The Image Library updates each time you start Prisma to reflect the contents of the Images folder.\n\nIf you add, remove, or replace files while it is running, you will need to use the **Refresh** button to make those changes visible in the Image Library.\n\nIf your library has a lot of photos, you can use the **Expand** button (to the right of Refresh) to make it easier to browse.",
    target: "image.library-maintenance",
    placementGroup: "basics-image-library",
  }),
  step({
    id: "choose-image",
    title: "Select the tutorial image",
    body: "For this guide, we will use **{{tutorialImage}}** as the source image.\n\nSelect it to continue.",
    target: "basics.tutorial-image",
    placementGroup: "basics-image-library",
    completionMode: completion("event", {
      event: "image.selected",
      predicate_id: "basics.tutorial-image-selected",
      accept_preexisting: true,
    }),
  }),
  step({
    id: "image-preview",
    title: "Preview and Adjustments",
    body: "The large preview shows how your image will appear as a lithophane, including any adjustments.\n\nThe **Adjustments** panel controls the lithophane’s shape, physical size, framing, and image appearance. These changes do not alter the original image file and are only used within Prisma.",
    target: "image.preview-adjustments",
    placementGroup: "basics-image-adjustments",
    placements: ["left", "bottom", "top", "right"],
  }),
  step({
    id: "image-adjustments",
    title: "Adjustments panel",
    body: "The Adjustments panel sets the lithophane’s shape and physical size, how the photograph fits inside it, and the photograph’s appearance.\n\nWe will look at its Size and Image controls next.",
    target: "image.adjustments",
    placementGroup: "basics-image-adjustments",
    placements: ["left", "bottom", "top", "right"],
  }),
  step({
    id: "aspect-ratios",
    title: "Aspect-ratio choices",
    body: "The Size tab has several ways to control how an image’s framing relates to the lithophane’s dimensions:\n\n• **W × H** allows use of any aspect ratio. Changing a dimension will change how an image is framed and vice versa.\n• **Ratio** allows you to specify an arbitrary aspect ratio. Common ratios are available as presets.\n• **Image** keeps the source image’s aspect ratio.",
    target: "image.aspect-experiment",
    placementGroup: "basics-image-adjustments",
    placements: ["left", "bottom", "top", "right"],
  }),
  step({
    id: "crop-fit",
    title: "Crop-fit shortcuts",
    body: "The first Crop Fit button resets the image zoom and centers it. The other two resize the frame to use the source image’s full width or full height.\n\nEach button provides a quick way to establish an initial crop; you can continue refining the framing afterward. Feel free to try all three.",
    target: "image.crop-fit",
    placementGroup: "basics-image-adjustments",
    placements: ["left", "bottom", "top", "right"],
  }),
  step({
    id: "interactive-framing",
    title: "Interactive framing",
    body: "Use the mouse wheel within the image framing display to zoom in on your image. If the image extends beyond its frame, you can drag the image to change its relative position.\n\nScale and Rotate allow for precise control of these properties. The buttons beneath can be used to rotate an image 90 degrees or to mirror it.",
    target: "image.framing",
    placementGroup: "basics-image-adjustments",
    placements: ["left", "bottom", "top", "right"],
  }),
  step({
    id: "physical-dimensions",
    title: "Physical dimensions",
    body: "Width and Height set the lithophane’s physical dimensions. The lock buttons prevent a specified value from being changed unintentionally. The width and the height must both be divisible by the Solve Pitch.",
    target: "image.physical-dimensions",
    placementGroup: "basics-image-adjustments",
    placements: ["left", "bottom", "top", "right"],
  }),
  step({
    id: "border",
    title: "Optional printed border",
    body: "**Border** allows you to add a raised frame around the perimeter of a lithophane. It will be printed with the same color filament as the rest of a lithophane’s upper surface. The uniform thickness provides strength and can aid in mounting your print in a frame.\n\nBe sure to account for the size of the border when choosing your dimensions.",
    target: "image.border",
    placementGroup: "basics-image-adjustments",
    placements: ["left", "bottom", "top", "right"],
  }),
  step({
    id: "open-image-adjustments",
    title: "Open the Image controls",
    body: "Select Image at the top of the Adjustments panel to open the image-adjustment controls. The guide will continue automatically.",
    target: "image.adjustment-image-tab",
    placementGroup: "basics-image-adjustments",
    placements: ["left", "bottom", "top", "right"],
    completionMode: completion("event", {
      event: "image.adjustment-tab.changed",
      predicate_id: "image.adjustment-tab-image",
      accept_preexisting: true,
    }),
    allowSkip: false,
  }),
  step({
    id: "appearance",
    title: "Image appearance",
    body: "Although Prisma is meant for color lithophanes, you can toggle the image mode using **B/W** and **Color**.\n\nThe sliders in the upper half influence the brightness and darkness in your image. The sliders in the lower half influence color in your image. Feel free to experiment with them if they are unfamiliar.",
    target: "image.appearance",
    placementGroup: "basics-image-adjustments",
    placements: ["left", "bottom", "top", "right"],
  }),
  step({
    id: "reset-image-controls",
    title: "Reset the image controls",
    body: "The **Reset** button restores the Size and Image controls in the Adjustments panel to their defaults.\n\nReset does not change whether a border is enabled or disabled. Please turn it off.\n\nPlease click **Reset** to clear any changes you may have tried and to continue in this guide.",
    target: "image.reset-framing",
    placementGroup: "basics-image-adjustments",
    placements: ["left", "bottom", "top", "right"],
    completionMode: completion("event", {
      event: "image.controls-reset",
      predicate_id: "basics.image-reset",
      accept_preexisting: false,
    }),
    allowSkip: false,
  }),
  step({
    id: "tutorial-canvas",
    title: "Set the tutorial canvas",
    body: "By default, the proportions of your lithophane will match the aspect ratio of the image. If you know the dimension one of your sides needs to be, you do not have to calculate the other.\n\nIf you change the height to 120 mm, the width will automatically change to 90 mm. Once the size is set to 90 × 120 mm, select **Next** to continue.",
    target: "image.tutorial-canvas",
    placementGroup: "basics-image-adjustments",
    placements: ["left", "bottom", "top", "right"],
    completionMode: completion("manual", {
      predicate_id: "basics.canvas-ready",
    }),
    allowSkip: false,
  }),
  step({
    id: "image-summary",
    title: "Resolution summary",
    body: "Image Size is the source image’s resolution. Print Size is the physical size of the lithophane. Rendered Size is the pixel grid that Prisma will solve.\n\nA larger canvas or a smaller Solve Pitch (the physical spacing between pixels in Prisma’s solver grid) creates more solve pixels and requires more time.",
    target: "image.summary",
    placementGroup: "basics-image-adjustments",
  }),
  step({
    id: "open-palette",
    title: "Continue to Palette",
    body: "Select **Palette** in the top bar to continue.",
    target: "workflow.palette",
    placements: ["bottom", "right", "top", "left"],
    viewportAnchor: "center",
    completionMode: completion("event", {
      event: "tab.changed",
      predicate_id: "tab.creation",
      accept_preexisting: false,
    }),
    allowSkip: false,
  }),
  step({
    id: "palette-introduction",
    title: "Palette: choose your filaments",
    body: "Recall that a palette is the set of filaments Prisma will use to recreate the colors in an image.\n\nYou can create a palette yourself, or you can let Prisma automatically recommend palettes that are tailored to your image.",
    target: null,
    overlayMode: "full-scrim",
    placements: [],
  }),
  step({
    id: "palette-methods",
    title: "Building a palette",
    body: "Auto-Suggest recommends palettes with filaments that combine to reproduce the colors in your image.\n\nIt will only include filaments that are selected in this panel. Deselecting a filament prevents Auto-Suggest from including it in palettes.\n\nNote that whichever filament you choose for the white cap and base will never be included in palette suggestions. This selection is made in **Settings**.",
    target: "palette.autosuggest-overview",
    placementGroup: "basics-palette-suggestions",
    placements: ["bottom", "right", "top", "left"],
  }),
  step({
    id: "autosuggest-controls",
    title: "Auto-Suggest controls",
    body: "**Palette Colors** specifies the exact number of colored filaments in each suggested palette, while **Suggestions** controls how many palettes Auto-Suggest will return.\n\nThe **Solve Mode** selector controls whether Auto-Suggest will recommend palettes meant for Color or Luminance solve modes. This mode is discussed in [PLACEHOLDER FOR NAME OF GUIDE WHEN I WRITE IT].",
    target: "palette.autosuggest-controls",
    placementGroup: "basics-palette-suggestions",
    placements: ["left", "bottom", "top", "right"],
  }),
  step({
    id: "candidate-filaments",
    title: "Auto-Suggest filaments",
    body: "Every active filament that can be used for color is already selected here.\n\nThis does not add every selected filament to one palette. It tells Auto-Suggest which filaments it may combine when building suggestions.\n\nThe filament reserved for the white base and cap cannot also be selected as a color. Leave the current selection unchanged for this guide.",
    target: "palette.candidates",
    placementGroup: "basics-palette-suggestions",
    placements: ["right", "bottom", "top", "left"],
  }),
  step({
    id: "suggest-palettes",
    title: "Suggest palettes",
    body: "Auto-Suggest ranks palettes using a metric that scores them solely on their potential to reproduce colors in your source image. It will return the number of palettes you requested, ordered by that ranking.\n\nFor this guide, confirm that **Palette Colors** is set to exactly 3 and **Suggestions** is at least 2.\n\nSelect **Suggest Palettes** to continue. This should only take a few seconds.",
    target: "palette.suggest",
    placementGroup: "basics-palette-suggestions",
    completionMode: completion("event", {
      event: "palette.suggestions.completed",
      predicate_id: "basics.two-suggestions-ready",
    }),
    allowSkip: false,
  }),
  step({
    id: "add-suggestions",
    title: "Suggested palettes",
    body: "The palettes are each shown as a card that displays its filaments and the score used to rank it.\n\nA higher score does not mean a palette will make a better-looking lithophane. Think about the scores as representing a palette’s *potential*. You have to actually try solving an image with a palette to find out how it will look.\n\nFor this guide, you will use the two highest-ranked results: **{{paletteA}}** and **{{paletteB}}**.\n\nSelect **Add to Deck** on each to add them to the Palette Deck.",
    target: "palette.suggestions",
    placementGroup: "basics-palette-suggestions",
    completionMode: completion("event", {
      event: "palette.deck.updated",
      predicate_id: "basics.tutorial-palettes-in-deck",
    }),
    allowSkip: false,
  }),
  step({
    id: "palette-deck",
    title: "The Palette Deck",
    body: "The Palette Deck contains palettes you are working with during a session. You will regularly add and remove palettes from the deck.\n\nYou can remove a single palette using its **×** button. You can remove all palettes from the deck using **Clear**. A second click is required to confirm either action.\n\nPalettes are cleared from the deck when you close Prisma. You can save a palette by selecting **⋯** and then **Save Palette**. Saved palettes can be added to the deck using **Load**.",
    target: "palette.deck",
  }),
  step({
    id: "manual-palette-add",
    title: "Build a Manual palette",
    body: "The Manual builder is now open.\n\nChoose one or more colored filaments in any order, then select Add to Deck. The guide will continue after your new palette appears in the sidebar Deck.",
    target: "palette.manual",
    placements: ["right", "bottom", "top", "left"],
    completionMode: completion("event", {
      event: "palette.deck.updated",
      predicate_id: "basics.manual-card-added",
    }),
    allowSkip: false,
  }),
  step({
    id: "manual-palette-remove",
    title: "Remove the Manual palette",
    body: "This is the manual palette that you just added. You will now remove it from the deck.\n\nSelect its × button once; it changes to ! to ask for confirmation. Select it a second time to remove the card.\n\nThe two suggested tutorial palettes will remain.",
    target: "basics.manual-card",
    placementGroup: "basics-palette-deck",
    placements: ["right", "bottom", "top", "left"],
    completionMode: completion("event", {
      event: "palette.deck.updated",
      predicate_id: "basics.manual-card-removed",
    }),
    allowSkip: false,
  }),
  step({
    id: "open-palette-variant",
    title: "Create a palette variant",
    body: "A variant begins as a copy of an existing palette that you can modify without changing the original.\n\nOn **{{paletteA}}**, open the **⋯** menu and select **Create Variant**.",
    target: "basics.palette-a",
    placementGroup: "basics-palette-deck",
    placements: ["right", "bottom", "top", "left"],
    participatingSurfaces: ["#deckCardMenu"],
    completionMode: completion("event", {
      event: "palette.variant.started",
      predicate_id: "basics.palette-variant-started",
    }),
    allowSkip: false,
  }),
  step({
    id: "add-palette-variant",
    title: "Modify and add the variant",
    body: "The Manual builder contains a copy of the original palette. Remove or replace at least one filament, then select **Add Variant to Deck**.",
    target: "palette.manual",
    placements: ["right", "bottom", "top", "left"],
    completionMode: completion("event", {
      event: "palette.deck.updated",
      predicate_id: "basics.palette-variant-added",
    }),
    allowSkip: false,
  }),
  step({
    id: "remove-palette-variant",
    title: "Remove the palette variant",
    body: "This is the variant palette that you just added. You will now remove it from the Deck.\n\nSelect its × button once, then select ! to confirm its removal.",
    target: "basics.variant-card",
    placementGroup: "basics-palette-deck",
    placements: ["right", "bottom", "top", "left"],
    completionMode: completion("event", {
      event: "palette.deck.updated",
      predicate_id: "basics.palette-variant-removed",
    }),
    allowSkip: false,
  }),
  step({
    id: "palette-saving-pointer",
    title: "Save palettes for later",
    body: "Palettes can also be saved so that you can load them into the Palette Deck in later sessions. The **Saving & Loading** guide, available from **Help & Guides**, explains how to save, load, and delete saved palettes.",
    target: "palette.deck",
  }),
  step({
    id: "activate-first",
    title: "Activate first palette",
    body: "Select {{paletteA}} in the Deck. The highlighted card is the active palette used by the next solve.",
    target: "basics.palette-a",
    placementGroup: "basics-palette-deck",
    completionMode: completion("event", {
      event: "palette.deck.activated",
      predicate_id: "basics.palette-a-active",
      accept_preexisting: true,
    }),
    allowSkip: false,
  }),
  step({
    id: "settings-introduction",
    title: "Settings: control the solve",
    body: "**Settings** controls how Prisma turns your image and the filaments in your active palette into a printable layer plan. This process is called solving an image.\n\nPrisma exposes many parameters so you can customize this process, but you only need to understand a small set of them to use Prisma effectively.",
    target: null,
    overlayMode: "full-scrim",
    placements: [],
  }),
  step({
    id: "lithophane-stack",
    title: "The structure of a lithophane",
    body: "A color lithophane is built from a white base, a stack of colored filament layers, and a white cap on its viewing side. Several settings control the dimensions of this structure.",
    target: null,
    overlayMode: "full-scrim",
    placements: [],
    companion: {
      layout: "single",
      items: [{
        type: "image",
        src: "/assets/guides/settings-drawer/lithophane-stack-placeholder-v1.svg",
        alt: "Cross-section of a lithophane showing its white base, color layers, white cap, layer height, pixel size, and maximum thickness",
        expandable: true,
      }],
    },
  }),
  step({
    id: "open-settings",
    title: "Open Settings",
    body: "This guide uses a prepared Settings Profile containing the tutorial values.\n\nSelect **Settings** to open the drawer and review them.",
    target: "topbar.settings",
    completionMode: completion("event", {
      event: "settings.opened",
      predicate_id: "settings.drawer-open",
    }),
  }),
  step({
    id: "settings-profile",
    title: "The Settings drawer",
    body: "The Settings drawer contains every parameter Prisma will use for the next **Solve**.\n\nYou may change these settings at any time. A change affects only solves started afterward; it does not alter any completed results.",
    target: "settings.drawer-overview",
    placementGroup: "basics-settings",
    placements: ["left", "bottom", "top", "right"],
    completionMode: completion("manual", {
      predicate_id: "basics.tutorial-profile-ready",
    }),
    allowSkip: false,
  }),
  step({
    id: "settings-solve-resolution",
    title: "Solve resolution",
    body: "Leave **Solve Mode** set to **Color** for this guide.\n\n**Solve Pitch** is the physical size of each square cell in Prisma’s solve grid. A smaller value can preserve finer details, but it also increases solving time. Prisma changes it in whole increments of the active Extrusion Width.\n\nKeep the tutorial value of 0.4 mm.",
    target: "settings.essentials-resolution",
    placementGroup: "basics-settings",
    placements: ["left", "bottom", "top", "right"],
  }),
  step({
    id: "settings-layer-construction",
    title: "Layer structure and materials",
    body: "These settings correspond to the lithophane structure shown in the earlier diagram:\n\n• **Layer Height** is the thickness of each printed layer and must exactly match the layer height used by your slicer.\n• **Max Thickness** limits the combined thickness of the base, color layers, and white cap.\n• **Base Thickness** controls the thickness of the solid white base.\n• **Min Cap Layers** sets the minimum thickness of the continuous white boundary cap.\n• **Base/Cap Filament** selects the white filament used for both surfaces.\n\nKeep the tutorial values unchanged.",
    target: "settings.essentials-construction",
    placementGroup: "basics-settings",
    placements: ["left", "bottom", "top", "right"],
  }),
  step({
    id: "settings-profiles",
    title: "Settings Profiles",
    body: "A Settings Profile saves the complete collection of settings so you can reuse it later.\n\n**Save** updates the loaded named profile. If the current profile cannot be overwritten, Prisma offers to create a new one. **Save As...** always creates a new named profile. Use **Load** to browse, load, and manage saved profiles.",
    target: "settings.profiles",
    placementGroup: "basics-settings",
    placements: ["left", "bottom", "top", "right"],
  }),
  step({
    id: "preprocessing-solver",
    title: "Preprocessing and the Color Solver",
    body: "**Preprocessing** prepares the adjusted image for the solver. Its optional modules can reduce noise, smooth printable-scale features, or reshape tone and saturation.\n\nThe **Color Solver** controls how Prisma matches printable colors, plans regions that share filament recipes, and refines those regions. The basic view exposes the most commonly useful controls; Advanced reveals the rest.\n\nLeave these controls unchanged for the tutorial image.",
    target: "settings.preprocessing-solver",
    placementGroup: "basics-settings",
    placements: ["left", "bottom", "top", "right"],
  }),
  step({
    id: "white-cap",
    title: "White Cap",
    body: "The **White Cap** covers the color stack on the viewing side of the lithophane. Its controls are divided into two parts:\n\n• **Boundary Cap** maintains structural coverage and controls broad surface smoothing. It respects the minimum established by **Min Cap Layers** in Essentials.\n• **Detail Cap** adds finer relief that can preserve appearance. **Max Detail Layers** limits the number of additional detail layers.\n\nKeep the tutorial profile’s White Cap settings unchanged.",
    target: "settings.white-cap",
    placementGroup: "basics-settings",
    placements: ["left", "bottom", "top", "right"],
  }),
  step({
    id: "advanced-settings",
    title: "Advanced settings",
    body: "Select **Advanced: Off** to reveal less frequently changed controls. This changes only what the drawer displays; it does not change any setting values.\n\nReview the additional controls, then select **Advanced: On** to turn Advanced off and continue.",
    target: "settings.advanced",
    placementGroup: "basics-settings",
    placements: ["left", "bottom", "top", "right"],
    completionMode: completion("event", {
      event: "settings.advanced-changed",
      predicate_id: "basics.settings-detour-ready",
    }),
  }),
  step({
    id: "close-settings",
    title: "Close Settings",
    body: "Each solve captures a copy of the current settings when it begins. Later changes in the drawer do not alter the settings retained by that solve.\n\nClose Settings to continue.",
    target: "settings.drawer",
    placementGroup: "basics-settings",
    placements: ["left", "bottom", "top", "right"],
    completionMode: completion("event", {
      event: "settings.closed",
      predicate_id: "settings.drawer-closed",
    }),
  }),
  step({
    id: "solve-first",
    title: "Solve: first palette",
    body: "Select Solve.\n\nA solve can be started from any workflow page. It uses the prepared image, active palette, and current settings at the moment it begins. Prisma will move to Preview while it works.",
    target: "topbar.solve",
    completionMode: completion("event", {
      event: "solve.completed",
      predicate_id: "basics.first-solve-complete",
    }),
    allowSkip: false,
  }),
  step({
    id: "preview-introduction",
    title: "Preview: compare and inspect results",
    body: "Preview is where Prisma collects completed solve runs so you can compare their predicted appearance, inspect their printable structures, and review the settings that produced them.\n\nA run is one solve result created from a particular image, palette, and collection of settings.\n\nWe will create a second run before exploring the available inspection tools.",
    target: null,
    overlayMode: "full-scrim",
    placements: [],
  }),
  step({
    id: "preview-arrival",
    title: "First solve result",
    body: "You are now in Preview. The completed run appears in Solve History, while its predicted result appears in the comparison area.\n\nThese two regions stay linked as you add and select runs.",
    target: "preview.overview",
    placementGroup: "basics-preview",
    placements: ["left", "bottom", "top", "right"],
  }),
  step({
    id: "activate-second",
    title: "Activate the second palette",
    body: "Without leaving Preview, select {{paletteB}} in the Deck. The guide will continue when it becomes the active palette.",
    target: "basics.palette-b",
    completionMode: completion("event", {
      event: "palette.deck.activated",
      predicate_id: "basics.palette-b-active",
      accept_preexisting: true,
    }),
    allowSkip: false,
  }),
  step({
    id: "solve-second",
    title: "Solve the second palette",
    body: "Select Solve again.\n\nSolve is available throughout the workflow and uses the active palette, so you do not need to leave Preview. This second run will give you two results to compare.",
    target: "topbar.solve",
    completionMode: completion("event", {
      event: "solve.completed",
      predicate_id: "basics.second-solve-complete",
    }),
    allowSkip: false,
  }),
  step({
    id: "compare-runs",
    title: "Compare the solves",
    body: "Both guide runs should now be selected and displayed side by side in the comparison area.\n\nThis is where you judge the visible differences between palettes. Select Next after looking at both results.",
    target: "preview.comparison",
    placementGroup: "basics-preview",
    placements: ["left", "bottom", "top", "right"],
    completionMode: completion("manual", {
      predicate_id: "basics.both-runs-selected",
    }),
    allowSkip: false,
  }),
  step({
    id: "solve-history",
    title: "Solve History",
    body: "**Solve History** contains one card for each completed run. Select cards to choose which results appear in the comparison area.\n\nEach card also contains controls for reviewing the settings used by that solve, saving the run, or removing it. Solve History only lasts for the current session unless you save a run.",
    target: "preview.history",
    placementGroup: "basics-preview",
    placements: ["left", "bottom", "top", "right"],
  }),
  step({
    id: "preview-views",
    title: "The Predicted view",
    body: "**Predicted** is the standard Preview view. It shows Prisma’s estimate of how each selected solve will look when illuminated.\n\nSelect a preview image to open a larger view. The other Preview views provide more specialized information and are not needed for this guide.",
    target: "preview.views",
    placementGroup: "basics-preview",
    placements: ["bottom", "left", "top", "right"],
  }),
  step({
    id: "open-export",
    title: "Open Export",
    body: "Export creates files for one completed run at a time. Open Export.",
    target: "workflow.export",
    placements: ["bottom", "right", "top", "left"],
    completionMode: completion("event", {
      event: "tab.changed",
      predicate_id: "tab.export",
      accept_preexisting: true,
    }),
  }),
  step({
    id: "export-introduction",
    title: "Export: create print files",
    body: "Export converts one completed run into files for slicing and printing.\n\nHere you choose the run and how its geometry should be packaged. Prisma then creates the meshes, filament instructions, and mesh report from that run’s stored data.\n\nExporting does not repeat the solve or change the completed run.",
    target: null,
    overlayMode: "full-scrim",
    placements: [],
  }),
  step({
    id: "export-choices-overview",
    title: "Export choices",
    body: "Output format chooses one bundled 3MF or separate STL files. Mesh method controls how the solved surface becomes printable geometry, and Mesh detail controls reconstruction scale for the field-derived method.\n\nThese choices affect file packaging and mesh construction; they do not repeat or change the solve.",
    target: "export.options",
    placementGroup: "basics-export",
    placements: ["left", "bottom", "top", "right"],
  }),
  step({
    id: "select-export-run",
    title: "Select the export run",
    body: "Export begins with one completed run.\n\nSelect the run made with {{paletteA}}. Its preview and dimensions confirm which solve will be exported.",
    target: "basics.export-run-a",
    placementGroup: "basics-export",
    completionMode: completion("event", {
      event: "export.run-selected",
      predicate_id: "basics.export-run-a-selected",
      accept_preexisting: true,
    }),
    allowSkip: false,
  }),
  step({
    id: "export-options",
    title: "Print-file options",
    body: "Output format chooses one bundled 3MF or individual STL files. Mesh method chooses how the solved surface becomes geometry. Mesh detail controls reconstruction scale for the field-derived method.\n\nUse Single 3MF file, Field-derived white cap, and 4x balanced, then select Next.",
    target: "export.options",
    placementGroup: "basics-export",
    placements: ["left", "bottom", "top", "right"],
    completionMode: completion("manual", {
      predicate_id: "basics.export-options-ready",
    }),
    allowSkip: false,
  }),
  step({
    id: "generate-files",
    title: "Generate Print Files",
    body: "Select Generate Print Files.\n\nPrisma builds 3D model files and filament-loading or swap instructions from the selected run’s stored data.",
    target: "export.generate",
    placementGroup: "basics-export",
    completionMode: completion("event", {
      event: "export.completed",
      predicate_id: "basics.export-complete",
    }),
    allowSkip: false,
  }),
  step({
    id: "export-results",
    title: "Files are already saved",
    body: "The export record preserves its options and lists generated files, filament-loading or swap instructions, and the mesh report.\n\nThese files are already saved in the Output folder shown below. Use Open Folder to view them.\n\nDownload .zip creates a packaged copy in a location you choose. Use it only when you want a copy outside the workspace.",
    target: "export.results",
    placementGroup: "basics-export",
    placements: ["left", "top", "bottom", "right"],
  }),
  step({
    id: "complete",
    title: "Project complete",
    body: "You completed Prisma Generator’s normal workflow: selected the Tutorial Printer profile, prepared a source image, built and compared palettes, reviewed settings, made two solves, inspected Preview, and generated print files.\n\nWhen this guide closes, Prisma will remove its tutorial workspace and restore your previous Settings Profile, printer, Extrusion Width, filament choices, and related controls.\n\nHappy printing!",
    target: null,
    placements: [],
    allowSkip: false,
  }),
]);

const BASICS_LESSONS_BY_ID = new Map(BASICS_LESSONS.map(current => [current.id, current]));

function lessons(...ids) {
  return Object.freeze(ids.map((id) => {
    const current = BASICS_LESSONS_BY_ID.get(id);
    if (!current) throw new Error(`Unknown shared Basics lesson: ${id}`);
    return current;
  }));
}
const BASICS_INTRODUCTION = lessons(
  "introduction",
  "core-terminology",
  "lithophane-image-principle",
  "prisma-creation-overview",
  "workflow",
  "printer-select",
  "tutorial-extrusion-width",
);
const BASICS_IMAGE_SPINE = lessons(
  "image-introduction",
  "image-library",
  "image-library-maintenance",
  "choose-image",
  "image-preview",
  "reset-image-controls",
  "tutorial-canvas",
  "open-palette",
);
const BASICS_PALETTE_SPINE = lessons(
  "palette-introduction",
  "palette-methods",
  "autosuggest-controls",
  "suggest-palettes",
  "add-suggestions",
  "palette-deck",
  "activate-first",
);
const BASICS_SETTINGS_SPINE = lessons(
  "settings-introduction",
  "lithophane-stack",
  "open-settings",
  "settings-profile",
  "settings-solve-resolution",
  "settings-layer-construction",
  "close-settings",
  "solve-first",
);
const BASICS_PREVIEW_SPINE = lessons(
  "preview-introduction",
  "preview-arrival",
  "activate-second",
  "solve-second",
  "compare-runs",
  "open-export",
);
const BASICS_EXPORT_SPINE = lessons(
  "export-introduction",
  "select-export-run",
  "export-options",
  "generate-files",
  "export-results",
  "complete",
);
const BASICS_STEPS = Object.freeze([
  ...BASICS_INTRODUCTION,
  ...BASICS_IMAGE_SPINE,
  ...BASICS_PALETTE_SPINE,
  ...BASICS_SETTINGS_SPINE,
  ...BASICS_PREVIEW_SPINE,
  ...BASICS_EXPORT_SPINE,
]);

const BASICS_DETOURS = Object.freeze([
  detour({
    id: "image-controls",
    label: "Image Controls",
    description: "Explore framing, appearance, borders, and physical-size controls.",
    offerStepId: "image-preview",
    returnStepId: "image-preview",
    detourSteps: lessons(
      "image-adjustments",
      "aspect-ratios",
      "crop-fit",
      "interactive-framing",
      "physical-dimensions",
      "border",
      "image-summary",
      "open-image-adjustments",
      "appearance",
    ),
  }),
  detour({
    id: "palette-tools",
    label: "Palette Tools",
    description: "Build a Manual palette and create a variant of an existing palette.",
    offerStepId: "palette-deck",
    returnStepId: "palette-deck",
    detourSteps: lessons(
      "manual-palette-add",
      "manual-palette-remove",
      "open-palette-variant",
      "add-palette-variant",
      "remove-palette-variant",
      "palette-saving-pointer",
    ),
  }),
  detour({
    id: "settings-tools",
    label: "Settings",
    description: "Explore Settings Profiles, the Color Solver, White Cap, and Advanced controls without changing the tutorial values.",
    offerStepId: "settings-profile",
    returnStepId: "settings-profile",
    returnPredicateId: "basics.settings-detour-ready",
    detourSteps: lessons(
      "settings-profiles",
      "preprocessing-solver",
      "white-cap",
      "advanced-settings",
    ),
  }),
  detour({
    id: "preview-tools",
    label: "Preview",
    description: "Learn how Solve History and the standard Predicted view work.",
    offerStepId: "compare-runs",
    returnStepId: "compare-runs",
    detourSteps: lessons(
      "solve-history",
      "preview-views",
    ),
  }),
  detour({
    id: "export-choices",
    label: "Export Choices",
    description: "Learn what output format, mesh method, and mesh detail control.",
    offerStepId: "export-introduction",
    returnStepId: "export-introduction",
    detourSteps: lessons("export-choices-overview"),
  }),
]);

const STANDALONE_COMPLETIONS = Object.freeze({
  image: step({
    id: "image-guide-complete",
    title: "Image Guide complete",
    body: "You explored Prisma’s image framing and appearance controls and restored the tutorial image to its 90 × 120 mm borderless canvas.",
    target: null,
    placements: [],
    allowSkip: false,
  }),
  palette: step({
    id: "palette-guide-complete",
    title: "Palette Guide complete",
    body: "You prepared two suggested palettes, explored the Palette Deck and Manual builder, and left Palette A active.",
    target: null,
    placements: [],
    allowSkip: false,
  }),
  settings: step({
    id: "settings-guide-complete",
    title: "Settings Guide complete",
    body: "You reviewed the essential solve controls, Settings Profiles, the Color Solver, and White Cap, then returned Advanced to Off. Your previous Settings Profile will be restored when this guide closes.",
    target: null,
    placements: [],
    allowSkip: false,
  }),
  preview: step({
    id: "preview-guide-complete",
    title: "Preview Guide complete",
    body: "You created two tutorial solves, compared their Predicted results, and explored Solve History.",
    target: null,
    placements: [],
    allowSkip: false,
  }),
  export: step({
    id: "export-guide-complete",
    title: "Export Guide complete",
    body: "You created a tutorial solve, generated its print files, and reviewed where Prisma stores the resulting files and instructions.",
    target: null,
    placements: [],
    allowSkip: false,
  }),
});

const IMAGE_GUIDE_PREPARATION = lessons("printer-select", "tutorial-extrusion-width");
const IMAGE_GUIDE_CONTENT = Object.freeze([
  ...lessons(
    "image-introduction",
    "image-library",
    "image-library-maintenance",
    "choose-image",
    "image-preview",
  ),
  ...BASICS_DETOURS.find(item => item.id === "image-controls").steps,
  ...lessons("reset-image-controls", "tutorial-canvas"),
  STANDALONE_COMPLETIONS.image,
]);
const IMAGE_GUIDE_STEPS = Object.freeze([...IMAGE_GUIDE_PREPARATION, ...IMAGE_GUIDE_CONTENT]);

const PALETTE_GUIDE_PREPARATION = lessons(
  "printer-select",
  "tutorial-extrusion-width",
  "choose-image",
  "reset-image-controls",
  "tutorial-canvas",
  "open-palette",
);
const PALETTE_GUIDE_CONTENT = Object.freeze([
  ...lessons(
    "palette-introduction",
    "palette-methods",
    "candidate-filaments",
    "autosuggest-controls",
    "suggest-palettes",
    "add-suggestions",
    "palette-deck",
    "manual-palette-add",
    "manual-palette-remove",
    "open-palette-variant",
    "add-palette-variant",
    "remove-palette-variant",
    "palette-saving-pointer",
    "activate-first",
  ),
  STANDALONE_COMPLETIONS.palette,
]);
const PALETTE_GUIDE_STEPS = Object.freeze([...PALETTE_GUIDE_PREPARATION, ...PALETTE_GUIDE_CONTENT]);

const SETTINGS_GUIDE_STEPS = Object.freeze([
  ...lessons(
    "settings-introduction",
    "lithophane-stack",
    "open-settings",
    "settings-profile",
    "settings-solve-resolution",
    "settings-layer-construction",
    "settings-profiles",
    "preprocessing-solver",
    "white-cap",
    "advanced-settings",
    "close-settings",
  ),
  STANDALONE_COMPLETIONS.settings,
]);

const SOLVE_A_PREPARATION = lessons(
  "printer-select",
  "tutorial-extrusion-width",
  "choose-image",
  "reset-image-controls",
  "tutorial-canvas",
  "open-palette",
  "palette-methods",
  "autosuggest-controls",
  "suggest-palettes",
  "add-suggestions",
  "activate-first",
  "open-settings",
  "settings-profile",
  "close-settings",
  "solve-first",
);
const PREVIEW_GUIDE_CONTENT = Object.freeze([
  ...lessons(
    "preview-introduction",
    "preview-arrival",
    "activate-second",
    "solve-second",
    "compare-runs",
    "solve-history",
    "preview-views",
  ),
  STANDALONE_COMPLETIONS.preview,
]);
const PREVIEW_GUIDE_STEPS = Object.freeze([...SOLVE_A_PREPARATION, ...PREVIEW_GUIDE_CONTENT]);

const EXPORT_GUIDE_CONTENT = Object.freeze([
  ...lessons(
    "open-export",
    "export-introduction",
    "select-export-run",
    "export-choices-overview",
    "export-options",
    "generate-files",
    "export-results",
  ),
  STANDALONE_COMPLETIONS.export,
]);
const EXPORT_GUIDE_STEPS = Object.freeze([...SOLVE_A_PREPARATION, ...EXPORT_GUIDE_CONTENT]);

export {
  BASICS_INTRODUCTION, BASICS_IMAGE_SPINE, BASICS_PALETTE_SPINE,
  BASICS_SETTINGS_SPINE, BASICS_PREVIEW_SPINE, BASICS_EXPORT_SPINE,
  BASICS_STEPS, BASICS_DETOURS, IMAGE_GUIDE_PREPARATION, IMAGE_GUIDE_CONTENT,
  IMAGE_GUIDE_STEPS, PALETTE_GUIDE_PREPARATION, PALETTE_GUIDE_CONTENT,
  PALETTE_GUIDE_STEPS, SETTINGS_GUIDE_STEPS, SOLVE_A_PREPARATION,
  PREVIEW_GUIDE_CONTENT, PREVIEW_GUIDE_STEPS, EXPORT_GUIDE_CONTENT, EXPORT_GUIDE_STEPS,
};
