import { createCalibrationApi } from "./api/index.js";
import { createApplicationContext } from "./core/application-context.js";
import { initializeDom } from "./core/dom.js";
import { initializeApplicationState } from "./core/state.js";
import { installCoreDialogs } from "./core/dialogs.js";
import { installCoreFormatting } from "./core/formatting.js";
import { installCorePolling } from "./core/polling.js";
import { installCoreRendering } from "./core/rendering.js";
import { installCoreUi } from "./core/ui.js";
import { installFeaturesApplication } from "./features/application.js";
import { installFeaturesFilamentsIndex } from "./features/filaments/index.js";
import { installFeaturesGeometriesBuilder } from "./features/geometries/builder.js";
import { installFeaturesGeometriesBundles } from "./features/geometries/bundles.js";
import { installFeaturesGeometriesEditor } from "./features/geometries/editor.js";
import { installFeaturesGeometriesPreview } from "./features/geometries/preview.js";
import { installFeaturesImagesDialogs } from "./features/images/dialogs.js";
import { installFeaturesImagesIndex } from "./features/images/index.js";
import { installFeaturesLogbookEditor } from "./features/logbook/editor.js";
import { installFeaturesLogbookIndex } from "./features/logbook/index.js";
import { installFeaturesModelingProfiles } from "./features/modeling/profiles.js";
import { installFeaturesModelingReview } from "./features/modeling/review.js";
import { installFeaturesModelingWorkflow } from "./features/modeling/workflow.js";
import { installFeaturesOperationsBackup } from "./features/operations/backup.js";
import { installFeaturesOperationsGeometryDelete } from "./features/operations/geometry-delete.js";
import { installFeaturesOperationsMaintenance } from "./features/operations/maintenance.js";
import { installFeaturesOperationsMaintenanceWorkflow } from "./features/operations/maintenance-workflow.js";
import { installFeaturesOperationsReextract } from "./features/operations/reextract.js";
import { installFeaturesProcessingIndex } from "./features/processing/index.js";
import { installFeaturesProcessingManual } from "./features/processing/manual.js";
import { installFeaturesShellIndex } from "./features/shell/index.js";
import { startCalibrationApp } from "./features/application.js";

const api = createCalibrationApi();
const app = createApplicationContext({ api });
initializeDom(app);
installCoreDialogs(app);
installCoreFormatting(app);
installCorePolling(app);
installCoreRendering(app);
installCoreUi(app);
installFeaturesApplication(app);
installFeaturesFilamentsIndex(app);
installFeaturesGeometriesBuilder(app);
installFeaturesGeometriesBundles(app);
installFeaturesGeometriesEditor(app);
installFeaturesGeometriesPreview(app);
installFeaturesImagesDialogs(app);
installFeaturesImagesIndex(app);
installFeaturesLogbookEditor(app);
installFeaturesLogbookIndex(app);
installFeaturesModelingProfiles(app);
installFeaturesModelingReview(app);
installFeaturesModelingWorkflow(app);
installFeaturesOperationsBackup(app);
installFeaturesOperationsGeometryDelete(app);
installFeaturesOperationsMaintenance(app);
installFeaturesOperationsMaintenanceWorkflow(app);
installFeaturesOperationsReextract(app);
installFeaturesProcessingIndex(app);
installFeaturesProcessingManual(app);
installFeaturesShellIndex(app);
initializeApplicationState(app);
startCalibrationApp(app);
